name: deploy website
on :
  push:
    branches: 
      - master
jobs:
  deploy:
    runs -on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v2

        -name: deploy step
        run: echo "website deployed successfully"

